language: nix

jobs:
  include:
    - stage: Build
      env: TARGET=linux-exe
    - env: TARGET=windows-exe
    - env: TARGET=static-exe
    - stage: Package
      env: TARGET=release-zip

before_install:
- sudo mkdir -p /etc/nix
- echo "binary-caches = https://cache.nixos.org https://nixcache.reflex-frp.org https://static-haskell-nix.cachix.org https://hydra.iohk.io" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo "binary-cache-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= static-haskell-nix.cachix.org-1:Q17HawmAwaM1/BfIxaEDKAxwTOyRVhPG5Ji9K3+FvUU= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  - cachix use tttool
  - if [ -n "$CACHIX_SIGNING_KEY" ]; then cachix push tttool --watch-store; fi &
  - nix-build nix -A $TARGET
  - sleep 10 # to allow cachix finish uploading
